spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql:///food
    username: root
    password: 123123
mybatis-plus:
  type-aliases-package: com.sx.pojo
  mapper-locations: classpath:mapper/*.xml
  configuration:
    auto-mapping-behavior: full
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      id-type: assign_id

pagehelper:
  reasonable: true
  helper-dialect: mysql
  page-size-zero: true
